export { default as Home } from "./Home/Home";
export { default as SignIn } from "./SignIn/SignIn";
export { default as Skills } from "./Skills/Skills";
export { default as Projects } from "./Projects/Projects";
export { default as ProjectDetails } from "./ProjectDetails/ProjectDetails";
export { default as Contact } from "./Contact/Contact";
export { default as PageNotFound } from "./PageNotFound/PageNotFound";
export { default as AboutMe } from "./AboutMe/AboutMe";
export { default as Personal } from "./Personal/Personal";
